name: Docker Image CI
env:
  ip: ${{vars.SERVER_IP}}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job0-install:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Install Docker
      run: sudo chmod +777 code/* && sudo ./code/install_docker.sh
  job1-build:
    runs-on: self-hosted
    needs: job0-install
    steps:   
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: sudo docker build -t style-mix:$GITHUB_RUN_ID .
  job2-run:
    needs: [job0-install, job1-build]
    runs-on: self-hosted
    continue-on-error: true
    timeout-minutes: 1.5
    steps:
    - uses: actions/checkout@v1
    - name: RunContainer
      run: sudo docker run -p 9999:9999 --mount type=bind,source=/home/adminuser/actions-runner/_work/style-mix/style-mix,target=/style-content style-mix:$GITHUB_RUN_ID 
    - uses: actions/checkout@v1
    - name: move models
      run: sudo mv /home/adminuser/actions-runner/_work/style-mix/models /home/adminuser/actions-runner/_work/style-mix/style-mix/ 
    - uses: actions/checkout@v1
    - name: check status
      if: steps[*].outcome == 'cancelled' || ${{ cancelled() }}
      run: exit 0
    
    
