name: Docker Image CI
env:
  ip: ${{vars.SERVER_IP}}
  mod_path: /home/adminuser/actions-runner/_work/style-mix/style-mix/models/
  port: 9999
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job0-install:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Remove model for git cleanup check again
      run: sudo rm -r -f $mod_path
    - uses: actions/checkout@v1
    - name: Install Docker
      run: sudo chmod +777 code/* && sudo ./code/install_docker.sh
  job1-build:
    runs-on: self-hosted
    needs: job0-install
    steps:   
    - uses: actions/checkout@v1
    - name: Stops running container on port
      run: sudo chmod +777 code/* && sudo bash code/stop_port.sh $port
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: sudo docker build -t style-mix:$GITHUB_RUN_ID .
  job2-run:
    needs: [job0-install, job1-build]
    runs-on: self-hosted
    continue-on-error: true
    timeout-minutes: 1.5
    steps:
    - uses: actions/checkout@v1
    - name: RunContainer
      run: sudo docker run -p $port:$port --mount type=bind,source=/home/adminuser/actions-runner/_work/style-mix/style-mix,target=/style-content style-mix:$GITHUB_RUN_ID 
    - uses: actions/checkout@v1
    - name: check status
      if: steps[*].outcome == 'cancelled' || ${{ cancelled() }}
      run: exit 0
  job3-move:
    needs: [job0-install, job1-build, job2-run]
    runs-on: self-hosted
    continue-on-error: true
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v1
    - name: move models
      run: sudo cp -r /home/adminuser/actions-runner/_work/models /home/adminuser/actions-runner/_work/style-mix/style-mix/ 
    - uses: actions/checkout@v1
    - name: give permission  
      run: sudo chmod +777 -f $mod_path 
      
   
    
    
    
    
