name: Docker Image CI
env:
  ip: ${{vars.SERVER_IP}}
  mod_path: /home/adminuser/actions-runner/_work/style-mix/style-mix/models/
  base_path: /home/adminuser/actions-runner/_work/style-mix/style-mix
  port: 9999
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  job0-install:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Remove model for git cleanup check again
      run: sudo chmod +777 code/* && /bin/sh code/remove.sh $mod_path
    - uses: actions/checkout@v1
    - name: Install Docker
      run: sudo /bin/sh code/install_docker.sh
  job1-build:
    runs-on: self-hosted
    needs: job0-install
    steps:   
    - uses: actions/checkout@v1
    - name: Stops running container on port
      run: sudo chmod +777 code/* && sudo /bin/bash code/stop_port.sh $port
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: sudo docker build -t style-mix:$GITHUB_RUN_ID .
  job2-run:
    needs: [job0-install, job1-build]
    runs-on: self-hosted
    continue-on-error: true
    timeout-minutes: 1.5
    steps:
    - name: RunContainer
      run: sudo docker run -p $port:$port --mount type=bind,source=$base_path,target=/style-mix style-mix:$GITHUB_RUN_ID 
    - name: check status
      if: steps[*].outcome == 'cancelled' || ${{ cancelled() }}
      run: exit 0
  job3-move:
    needs: [job0-install, job1-build, job2-run]
    runs-on: self-hosted
    continue-on-error: true
    timeout-minutes: 1
    steps:
    - name: move models
      run: sudo cp -r /home/adminuser/actions-runner/_work/models /home/adminuser/actions-runner/_work/style-mix/style-mix 
    - name: give permission  
      run: sudo chmod +777 -f $mod_path 
  
      
   
    
    
    
    
